name: Workflow 2:Download

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: My Artifact
          
      - name: Read and Use Artifact File
        run: |
          cat send.csv  # 或者你可以使用其他适当的命令来读取文件内容
          python read.py
          # 在这里添加对 Artifact 文件的使用逻辑
          
      # 添加其他步骤或操作
