name: Main Workflow No.1(Run & Upload)

on:
  push:
    branches:
      - main  # 分支名称
  schedule:
    - cron: '1 */6 * * 1,2,3,4,5'  # UTC时间

jobs:
#   firstrun:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.8'  # 更改为你想要使用的Python版本

#     - name: Update pip
#       run: python -m pip install --upgrade pip
      
#     - name: Install dependencies
#       run: pip install -r req.txt  # 如果存在依赖，请在此处安装依赖
        
#     - name: Execute Python script
#       run: python main.py  # 替换为你的Python文件名称

    
#     - name: Save File as Artifact   #保存artifact
#       run:  cp SEND.csv ${{ github.workspace }}/send.csv
    
#     - name: Formal Art
#       uses: actions/upload-artifact@v2
#       with:
#         name: Formal Art
#         path: ${{ github.workspace }}/send.csv
        
        
  secondrun:
#     needs: firstrun
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: main.yml
        continue-on-error: true



      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 更改为你想要使用的Python版本


      - name: Update pip
        run: python -m pip install --upgrade pip


      - name: Install dependencies
        run: pip install -r req.txt  # 如果存在依赖，请在此处安装依赖

      - name: Execute walkpath
        run:  python walkpath.py 
        
      - name: Execute main.py Script
        run:           python main.py      

      - name: Save File as Artifact   #保存artifact
        run:  cp SEND.csv ${{ github.workspace }}/send.csv

      - name: Formal Art
        uses: actions/upload-artifact@v2
        with:
          name: Formal Art
          path: ${{ github.workspace }}/send.csv

